##### 1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [17]:
def compute(a):
    try:
        b = 5/a
        print(b)
    except Exception as y:
        print(y)
   

In [18]:
compute(0)

division by zero


##### 2.Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].


In [1]:
import random
def sentence():
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]
    sen = lambda x:x[random.randrange(len(x))]
    d = " ".join([sen(subjects),sen(verbs),sen(objects)])
    return d    

In [2]:
sentence()

'Americans  play Baseball'

In [3]:
b = sentence()
b

'Americans  play Baseball'

In [4]:
c = sentence()
c

'Americans  watch Baseball'

In [5]:
a = sentence()
a

'Indians watch Cricket'

In [6]:
d = sentence()
d

'Americans  play Baseball'

In [7]:
e= sentence()
e

'Indians watch Cricket'

In [8]:
f= sentence()
f

'Americans  watch Cricket'

In [9]:
g= sentence()
g

'Americans  play Baseball'

#### 3.Write a function so that the columns of the output matrix are powers of the input vector.

In [215]:
def vander(v,n, increasing = False):
    if not increasing:
        o = np.array([x**(n-1-i) for x in v for i in range(n)])
        print(o)
        o=o.reshape(v.size,n)
        print(o)
        return o
    else:
        o = np.array([x**i for x in v for i in range(n)])
        print(o)
        o = o.reshape(v.size,n)
        return o
    

In [213]:
vander(np.array([1,2,3]),3,True)

[1 1 1 1 2 4 1 3 9]


array([[1, 1, 1],
       [1, 2, 4],
       [1, 3, 9]])

In [214]:
vander(np.array([1,2,3]),3,False)

[1 1 1 4 2 1 9 3 1]
<class 'numpy.ndarray'>


array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])